[workflow]
name = "my-powershell"
version = "0.0.1"
author = "ddki"
description = "基于 Windows Terminal 对 powershell 增强"
repository = ""
proxy = ""

[[workflow.jobs]]
sort = 1
must = true
name = "scoop"
description = "Scoop 是 Windows 下的包管理工具"
url = "get.scoop.sh"

[[workflow.jobs.post_command]]
command = "scoop bucket add extras"

[[workflow.jobs.installs]]
command = "scoop_install.ps1"

[workflow.jobs.installs.args]
ScoopGlobalDir = "Scoop 全局 app 的安装目录"
scoopDir = "Scoop 的安装目录"
start = "-"

[[workflow.jobs]]
sort = 2
must = true
name = "Windows Terminal"
description = "Windows Terminal"

[[workflow.jobs.installs]]
command = "scoop install windows-terminal"

[[workflow.jobs]]
sort = 3
must = false
name = "coreutils"
description = "使用rust实现的跨平台GNU coreutils，包含了Linux上的常用命令。"

[[workflow.jobs.installs]]
command = "scoop install uutils-coreutils"

[[workflow.jobs]]
sort = 4
must = false
name = "oh-my-posh"
description = "PowerShell 主题"
url = "https://ohmyposh.dev/install.ps1"

[[workflow.jobs.pre_command]]
command = "pwsh"

[[workflow.jobs.installs]]
command = "scoop install https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/oh-my-posh.json"

[[workflow.jobs]]
sort = 5
must = false
name = "Terminal-Icons"
description = "PowerShell 模块，用于在终端中显示文件和文件夹图标。"

[[workflow.jobs.installs]]
command = "scoop install terminal-icons"

[[workflow.jobs]]
sort = 6
must = false
name = "PSCompletions"
description = "PowerShell 补全，默认启用 PowerShell 补全（git、scoop）"

[[workflow.jobs.pre_command]]
command = "pwsh"

[[workflow.jobs.post_command]]
command = "psc add git"

[[workflow.jobs.post_command]]
command = "psc add scoop"

[[workflow.jobs.installs]]
command = "Install-Module PSCompletions"

[[workflow.jobs.installs]]
command = "echo 'Import-Module PSCompletions' >> $PROFILE"
